include:
  - project: "segmentfault/devops/templates"
    file: ".docker-build-push.yml"
  - project: "segmentfault/devops/templates"
    file: ".deploy-helm.yml"

stages:
  - deploy-dev

"deploy-to-local-develop-environment":
  stage: deploy-dev
  extends: .deploy-helm
  only:
    - test
  variables:
    LoadBalancerIP: 10.0.10.98
    KubernetesCluster: dev
    KubernetesNamespace: "sf-web"
    InstallArgs: --set service.loadBalancerIP=${LoadBalancerIP} --set image.tag=latest --set replicaCount=1 --set serivce.targetPort=80
    ChartName: answer
    InstallPolicy: replace

