# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

env:
  - GO11MODULE=on
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io,direct
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

release:
  draft: true

builds:
  - id: build
    main: ./cmd/answer/.
    binary: answer
    ldflags: -s -w -X github.com/apache/incubator-answer/cmd.Version={{.RawVersion}} -X github.com/apache/incubator-answer/cmd.Revision={{.ShortCommit}} -X github.com/apache/incubator-answer/cmd.Time={{.Date}} -X github.com/apache/incubator-answer/cmd.BuildUser=goreleaser
    flags: -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: build-windows
    main: ./cmd/answer/.
    binary: answer
    ldflags: -s -w -X github.com/apache/incubator-answer/cmd.Version={{.RawVersion}} -X github.com/apache/incubator-answer/cmd.Revision={{.ShortCommit}} -X github.com/apache/incubator-answer/cmd.Time={{.Date}} -X github.com/apache/incubator-answer/cmd.BuildUser=goreleaser
    flags: -v
    goos:
      - windows
    goarch:
      - amd64




archives:
  - name_template: >-
      apache-answer-{{ .RawVersion }}-incubating-bin-{{ .Os }}-{{ .Arch }}
    files:
      - src: "docs/release/LICENSE"
        dst: LICENSE
      - src: "docs/release/NOTICE"
        dst: NOTICE
      - src: "docs/release/licenses/*"
        dst: licenses/
      - src: "DISCLAIMER"
        dst: DISCLAIMER
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true
  name_template: apache-answer-{{ .RawVersion }}-incubating-src
  prefix_template: "apache-answer-{{ .RawVersion }}-incubating-src/"

# goreleaser release --skip-validate  --skip-publish --clean

