# url path reserves the keywords list
questions:
  - ask
tags:
  - create
users:
  - unsubscribe
  - settings
  - login
  - register
  - account-recovery
  - change-email
  - password-reset
  - account-activation
  - confirm-new-email
  - account-suspended
  - confirm-email
  - auth-landing
