name: Build Dev Image

on:
  push:
    branches: [ "test","dev" ]


jobs:
  build:
    name: Build and Push
    runs-on: [self-hosted,linux]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.IMG_URL }}/${{ secrets.IMG_NAMESPACE }}/answer
        tags: |
          type=raw,value=latest


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to  Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.IMG_URL }}
        username: ${{ secrets.IMG_USERNAME }}
        password: ${{ secrets.IMG_PASSWORD }}


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./.github/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  sync-git:
    name: Sync to Git
    runs-on: [self-hosted,linux]
    needs:
      - build
    steps:
      - name: Sync to Gitlab
        uses: aiworklab/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:answerdev/answer.git
          destination-repo: ${{ secrets.GITLAB_REPO }}

